//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class element_order
    {
        public long id { get; set; }
        public long quentity { get; set; }
        public long order_id { get; set; }
        public long products_id { get; set; }
    
        public virtual products products { get; set; }
        public virtual sale sale { get; set; }
        public virtual supply supply { get; set; }
    }
}
