//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanAgreement
    {
        public long id { get; set; }
        public long supplier_id { get; set; }
        public long sum { get; set; }
        public long percent { get; set; }
        public System.TimeSpan start { get; set; }
        public System.TimeSpan end { get; set; }
        public long status_id { get; set; }
    
        public virtual status status { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
