//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class магазинEntities : DbContext
    {
        public магазинEntities()
            : base("name=магазинEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<discount> discount { get; set; }
        public virtual DbSet<element_order> element_order { get; set; }
        public virtual DbSet<loanAgreement> loanAgreement { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<sale> sale { get; set; }
        public virtual DbSet<salesman> salesman { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
        public virtual DbSet<supply> supply { get; set; }
    }
}
